
# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=joii
quarkus.datasource.password=joii5231
quarkus.datasource.jdbc.url=jdbc:postgresql://81.68.89.152:5432/aiide
quarkus.hibernate-orm.database.generation=none

# Appsmith session cookies for API access
aiide.appsmith-xsrf-token=312f1384-1b43-46be-84e9-3e4dc6423b49

# The following 4 configs have been migrated to system_configs DB table.
# These values are only used as initial seed defaults on first startup.
# After that, manage them via System Config UI (/system-config).
aiide.appsmith-session=c275d412-36bb-4f33-b0c7-a1e7c406a701
aiide.gitlab-api-base-url=http://10.177.152.5:3000
aiide.gitlab-repo-prefix=ssh://git@10.177.152.5:2222/srm-dev/
aiide.git-token=glpat-8_6t5pKNr61QHfu76Bw1QG86MQp1OjEH.01.0w09qnb0t

aiide.ssh-key-path=${SSH_KEY_PATH:../../sshkey/id_rsa}

aiide.redux-node-service-url=http://10.177.152.5/api/redux-node