[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx/access.log
stderr_logfile=/var/log/nginx/error.log

[program:backend]
command=java -jar /opt/backend/quarkus-run.jar
directory=/opt/backend
autostart=true
autorestart=true
environment=
    QUARKUS_HTTP_HOST="0.0.0.0",
    QUARKUS_HTTP_PORT="3100",
    QUARKUS_HTTP_CORS="true",
    QUARKUS_HTTP_CORS_ORIGINS="*",
    QUARKUS_LOG_CONSOLE_JSON="false"
stdout_logfile=/var/log/backend.log
stderr_logfile=/var/log/backend-error.log
