"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getMemberExpressionObjectFromProperty = exports.PeekOverlayExpressionIdentifier = exports.isFunctionPresent = exports.isJSFunctionProperty = exports.checkIfArgumentExistAtPosition = exports.checkIfCatchBlockExists = exports.checkIfThenBlockExists = exports.setQueryParam = exports.getQueryParam = exports.getFunctionParams = exports.canTranslateToUI = exports.getCallExpressions = exports.getFunctionNameFromJsObjectExpression = exports.getFunctionArguments = exports.setCatchBlockInQuery = exports.setThenBlockInQuery = exports.getThenCatchBlocksFromQuery = exports.setObjectAtPosition = exports.getFunctionName = exports.getMainAction = exports.getFunctionBodyStatements = exports.getActionBlocks = exports.setCallbackFunctionField = exports.replaceActionInQuery = exports.getFunction = exports.getFuncExpressionAtPosition = exports.setEnumArgumentAtPosition = exports.setTextArgumentAtPosition = exports.setModalName = exports.getModalName = exports.getEnumArgumentAtPosition = exports.getTextArgumentAtPosition = exports.NodeTypes = exports.SourceType = exports.ECMA_VERSION = exports.parseJSObject = exports.isTypeOfFunction = exports.getFunctionalParamsFromNode = exports.extractExpressionsFromCode = exports.entityRefactorFromCode = exports.extractIdentifierInfoFromCode = exports.getAST = exports.isCallExpressionNode = exports.isPropertyAFunctionNode = exports.isPropertyNode = exports.isLiteralNode = exports.isObjectExpression = exports.isVariableDeclarator = exports.isIdentifierNode = void 0;
const src_1 = require("./src");
Object.defineProperty(exports, "isIdentifierNode", { enumerable: true, get: function () { return src_1.isIdentifierNode; } });
Object.defineProperty(exports, "isVariableDeclarator", { enumerable: true, get: function () { return src_1.isVariableDeclarator; } });
Object.defineProperty(exports, "isObjectExpression", { enumerable: true, get: function () { return src_1.isObjectExpression; } });
Object.defineProperty(exports, "isLiteralNode", { enumerable: true, get: function () { return src_1.isLiteralNode; } });
Object.defineProperty(exports, "isPropertyNode", { enumerable: true, get: function () { return src_1.isPropertyNode; } });
Object.defineProperty(exports, "isPropertyAFunctionNode", { enumerable: true, get: function () { return src_1.isPropertyAFunctionNode; } });
Object.defineProperty(exports, "isCallExpressionNode", { enumerable: true, get: function () { return src_1.isCallExpressionNode; } });
Object.defineProperty(exports, "getAST", { enumerable: true, get: function () { return src_1.getAST; } });
Object.defineProperty(exports, "extractIdentifierInfoFromCode", { enumerable: true, get: function () { return src_1.extractIdentifierInfoFromCode; } });
Object.defineProperty(exports, "entityRefactorFromCode", { enumerable: true, get: function () { return src_1.entityRefactorFromCode; } });
Object.defineProperty(exports, "extractExpressionsFromCode", { enumerable: true, get: function () { return src_1.extractExpressionsFromCode; } });
Object.defineProperty(exports, "getFunctionalParamsFromNode", { enumerable: true, get: function () { return src_1.getFunctionalParamsFromNode; } });
Object.defineProperty(exports, "isTypeOfFunction", { enumerable: true, get: function () { return src_1.isTypeOfFunction; } });
Object.defineProperty(exports, "isFunctionPresent", { enumerable: true, get: function () { return src_1.isFunctionPresent; } });
Object.defineProperty(exports, "getMemberExpressionObjectFromProperty", { enumerable: true, get: function () { return src_1.getMemberExpressionObjectFromProperty; } });
// constants
const constants_1 = require("./src/constants");
Object.defineProperty(exports, "ECMA_VERSION", { enumerable: true, get: function () { return constants_1.ECMA_VERSION; } });
Object.defineProperty(exports, "SourceType", { enumerable: true, get: function () { return constants_1.SourceType; } });
Object.defineProperty(exports, "NodeTypes", { enumerable: true, get: function () { return constants_1.NodeTypes; } });
const jsObject_1 = require("./src/jsObject");
Object.defineProperty(exports, "parseJSObject", { enumerable: true, get: function () { return jsObject_1.parseJSObject; } });
Object.defineProperty(exports, "isJSFunctionProperty", { enumerable: true, get: function () { return jsObject_1.isJSFunctionProperty; } });
// action creator
const actionCreator_1 = require("./src/actionCreator");
Object.defineProperty(exports, "getTextArgumentAtPosition", { enumerable: true, get: function () { return actionCreator_1.getTextArgumentAtPosition; } });
Object.defineProperty(exports, "setTextArgumentAtPosition", { enumerable: true, get: function () { return actionCreator_1.setTextArgumentAtPosition; } });
Object.defineProperty(exports, "getEnumArgumentAtPosition", { enumerable: true, get: function () { return actionCreator_1.getEnumArgumentAtPosition; } });
Object.defineProperty(exports, "setEnumArgumentAtPosition", { enumerable: true, get: function () { return actionCreator_1.setEnumArgumentAtPosition; } });
Object.defineProperty(exports, "getModalName", { enumerable: true, get: function () { return actionCreator_1.getModalName; } });
Object.defineProperty(exports, "setModalName", { enumerable: true, get: function () { return actionCreator_1.setModalName; } });
Object.defineProperty(exports, "getFuncExpressionAtPosition", { enumerable: true, get: function () { return actionCreator_1.getFuncExpressionAtPosition; } });
Object.defineProperty(exports, "getFunction", { enumerable: true, get: function () { return actionCreator_1.getFunction; } });
Object.defineProperty(exports, "replaceActionInQuery", { enumerable: true, get: function () { return actionCreator_1.replaceActionInQuery; } });
Object.defineProperty(exports, "setCallbackFunctionField", { enumerable: true, get: function () { return actionCreator_1.setCallbackFunctionField; } });
Object.defineProperty(exports, "getActionBlocks", { enumerable: true, get: function () { return actionCreator_1.getActionBlocks; } });
Object.defineProperty(exports, "getFunctionBodyStatements", { enumerable: true, get: function () { return actionCreator_1.getFunctionBodyStatements; } });
Object.defineProperty(exports, "getMainAction", { enumerable: true, get: function () { return actionCreator_1.getMainAction; } });
Object.defineProperty(exports, "getFunctionName", { enumerable: true, get: function () { return actionCreator_1.getFunctionName; } });
Object.defineProperty(exports, "setObjectAtPosition", { enumerable: true, get: function () { return actionCreator_1.setObjectAtPosition; } });
Object.defineProperty(exports, "getThenCatchBlocksFromQuery", { enumerable: true, get: function () { return actionCreator_1.getThenCatchBlocksFromQuery; } });
Object.defineProperty(exports, "setThenBlockInQuery", { enumerable: true, get: function () { return actionCreator_1.setThenBlockInQuery; } });
Object.defineProperty(exports, "setCatchBlockInQuery", { enumerable: true, get: function () { return actionCreator_1.setCatchBlockInQuery; } });
Object.defineProperty(exports, "getFunctionArguments", { enumerable: true, get: function () { return actionCreator_1.getFunctionArguments; } });
Object.defineProperty(exports, "getFunctionNameFromJsObjectExpression", { enumerable: true, get: function () { return actionCreator_1.getFunctionNameFromJsObjectExpression; } });
Object.defineProperty(exports, "getCallExpressions", { enumerable: true, get: function () { return actionCreator_1.getCallExpressions; } });
Object.defineProperty(exports, "canTranslateToUI", { enumerable: true, get: function () { return actionCreator_1.canTranslateToUI; } });
Object.defineProperty(exports, "getFunctionParams", { enumerable: true, get: function () { return actionCreator_1.getFunctionParams; } });
Object.defineProperty(exports, "getQueryParam", { enumerable: true, get: function () { return actionCreator_1.getQueryParam; } });
Object.defineProperty(exports, "setQueryParam", { enumerable: true, get: function () { return actionCreator_1.setQueryParam; } });
Object.defineProperty(exports, "checkIfCatchBlockExists", { enumerable: true, get: function () { return actionCreator_1.checkIfCatchBlockExists; } });
Object.defineProperty(exports, "checkIfThenBlockExists", { enumerable: true, get: function () { return actionCreator_1.checkIfThenBlockExists; } });
Object.defineProperty(exports, "checkIfArgumentExistAtPosition", { enumerable: true, get: function () { return actionCreator_1.checkIfArgumentExistAtPosition; } });
const peekOverlay_1 = require("./src/peekOverlay");
Object.defineProperty(exports, "PeekOverlayExpressionIdentifier", { enumerable: true, get: function () { return peekOverlay_1.PeekOverlayExpressionIdentifier; } });
//# sourceMappingURL=index.js.map