export enum ErrorCode {
  // 通用
  INTERNAL_ERROR = "INTERNAL_ERROR",
  INVALID_REQUEST = "INVALID_REQUEST",

  // 参数缺失
  MISSING_PARAM = "MISSING_PARAM",

  // 会话
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_CREATE_FAILED = "SESSION_CREATE_FAILED",

  // 状态
  SLICE_NOT_FOUND = "SLICE_NOT_FOUND",
  ACTION_INVALID = "ACTION_INVALID",

  // 业务
  INIT_CRASH = "INIT_CRASH",
  TIMEOUT = "TIMEOUT",

  // 业务 - JS Action
  JS_COLLECTION_NOT_FOUND = "JS_COLLECTION_NOT_FOUND",

  // Eval
  EVAL_ERROR = "EVAL_ERROR",

  // Selector
  SELECTOR_NOT_FOUND = "SELECTOR_NOT_FOUND",
  SELECTOR_ERROR = "SELECTOR_ERROR",

  // 代理
  BACKEND_UNAVAILABLE = "BACKEND_UNAVAILABLE",
  BACKEND_TIMEOUT = "BACKEND_TIMEOUT",
  BACKEND_CONFIG_ERROR = "BACKEND_CONFIG_ERROR",
}
